FROM nginx:alpine

#ADD www/ /var/www/html/
#ADD config/main.php /var/www/html/lazy8/protected/config

ADD nginx/default.conf /etc/nginx/conf.d

#RUN mkdir -p /var/www/html/lazy8/assets && \
#    mkdir -p /var/www/html/lazy8/protected/runtime && \
#    mkdir -p /var/www/html/lazy8/protected/config && \
#    chmod -R 775 /var/www/html